<a href="https://colab.research.google.com/github/ayesha-119/Deep-Learning-BWF/blob/master/Task_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔴 **Task 10** 

**Topics: Introduction to Numpy, Numpy Arrays**

Resource: https://drive.google.com/file/d/1ILp88f3u_KgJ_nlhTSsAVGdmZlICGhhd/view?usp=share_link



Directions: Learn about Numpy arrays and try to make with single and multi dimensions, perform simple arithmetic operations using two multi dimensional arrays. Submit these practiced tasks on GitHub.

**Creating 1D array from lists**

In [4]:
import numpy as np

In [5]:
python_list = [3,2,5,8,4,9,7,6,1]
array = np.array(python_list)
array

array([3, 2, 5, 8, 4, 9, 7, 6, 1])

In [6]:
type(array)

numpy.ndarray

**Creating 2D array from list**

In [9]:
python_list_of_lists = [[3,2,5],
                        [9,7,1],
                        [4,3,6]
    
]
array2 = np.array(python_list_of_lists)

In [10]:
array2.ndim

2

In [12]:
array2.shape

(3, 3)

In [13]:
array2.dtype

dtype('int64')

**python lists** can contain different data types

In [14]:
python_list = ["beep", True, 34, 1.567, [3,2,5]]
python_list

['beep', True, 34, 1.567, [3, 2, 5]]

Numpy arrays can contain only single data type



*Use less space in memory





In [15]:
numpy_boolean_array = [[True , False] , [False , True]]
numpy_float_array = [1.9 , 5.4 , 9.8 , 6.3]

**Creating arrays from scratch:**


*   np.zeros()
*   np.random.random()
*   np.arange()







**Creating arrays: np.zeros()**

In [16]:
np.zeros((8,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**Creating arrays: np.random.random()**

In [17]:
np.random.random((8,6))

array([[0.85895615, 0.1049809 , 0.75391763, 0.64989055, 0.51211283,
        0.23203891],
       [0.454497  , 0.77529613, 0.72532728, 0.33846218, 0.15570028,
        0.84851284],
       [0.20164072, 0.10545679, 0.00945948, 0.04089028, 0.71992739,
        0.78082163],
       [0.93733482, 0.86729646, 0.41099334, 0.08241742, 0.131     ,
        0.19034144],
       [0.04170374, 0.28347764, 0.16616   , 0.557655  , 0.13259253,
        0.00219494],
       [0.21911359, 0.90913335, 0.99006185, 0.65315104, 0.20023747,
        0.91252141],
       [0.0404654 , 0.1925769 , 0.65888046, 0.54370177, 0.88393959,
        0.75141037],
       [0.43758295, 0.22571183, 0.22255707, 0.36296124, 0.56528219,
        0.60325647]])

**Creating arrays: np.aranage()**

In [18]:
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

In [ ]:
np.arange(4)

In [ ]:
np.arange(-3, 4, 3)

**Your first numpy array:**

Import NumPy using its generally accepted alias.
Convert sudoku_list into a NumPy array called sudoku_array.
Print the class type() of sudoku_array to check that your code has worked properly.

In [19]:
sudoku_list = [[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]

In [20]:
# Import NumPy
import numpy as np

# Convert sudoku_list into an array
sudoku_array = np.array(sudoku_list)

# Print the type of sudoku_array 
print(type(sudoku_array))


<class 'numpy.ndarray'>


**Create and print an array filled with zeros called zero_array, which has two rows and four columns.**

In [21]:
# Create an array of zeros which has four columns and two rows
zero_array = np.zeros((2,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Create and print an array of random floats between 0 and 1 called random_array, which has three rows and six columns.**

In [22]:
# Create an array of random floats which has six columns and three rows
random_array = np.random.random((3,6))
print(random_array)

[[0.9021592  0.02161225 0.36741749 0.207323   0.47628891 0.69117906]
 [0.32787576 0.07385999 0.26916661 0.28262871 0.14697242 0.93173259]
 [0.76814632 0.04761057 0.54868717 0.08781965 0.2055785  0.81394503]]


**Array Dimensionality:**

**3D Array**

In [28]:
array_1_2D = np.array([[3, 4],[7, 9]])
array_2_2D = np.array([[1, 3], [3, 1]])
array_3_2D = np.array([[6, 3], [7,4]])
array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
array_3D

array([[[3, 4],
        [7, 9]],

       [[1, 3],
        [3, 1]],

       [[6, 3],
        [7, 4]]])

**4D Array**

In [29]:
array_1_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
array_2_3D = np.array([array_2_2D, array_1_2D, array_3_2D])
array_3_3D = np.array([array_2_2D, array_3_2D, array_1_2D])
array_4_3D = np.array([array_3_2D, array_1_2D, array_2_2D])
array_5_3D = np.array([array_3_2D, array_2_2D, array_1_2D])

In [30]:
array_4D = np.array ( [array_1_3D, array_2_3D, array_3_3D, array_4_3D, array_5_3D])

In [31]:
array_4D

array([[[[3, 4],
         [7, 9]],

        [[1, 3],
         [3, 1]],

        [[6, 3],
         [7, 4]]],


       [[[1, 3],
         [3, 1]],

        [[3, 4],
         [7, 9]],

        [[6, 3],
         [7, 4]]],


       [[[1, 3],
         [3, 1]],

        [[6, 3],
         [7, 4]],

        [[3, 4],
         [7, 9]]],


       [[[6, 3],
         [7, 4]],

        [[3, 4],
         [7, 9]],

        [[1, 3],
         [3, 1]]],


       [[[6, 3],
         [7, 4]],

        [[1, 3],
         [3, 1]],

        [[3, 4],
         [7, 9]]]])

**Numpy data types:**

In [100]:
# The .dtype attribute
np.array([1,2,3,4]).dtype

dtype('int64')

In [101]:
# The default data type
int_array = np.array ([
    [3,2,1],
    [4,5,6]
])
int_array.dtype

dtype('int64')

In [103]:
# String data
np.array (["hello" , "numpy", "fam"]).dtype

dtype('<U5')

In [105]:
# dtype as an argument
float64_array = np.array( [1.32, 4, 123.456])
float64_array.dtype # 64 is the default value but you can change it

float32_array = np.array( [1.32, 4, 123.456], dtype = np.float32)
float32_array.dtype

dtype('float32')

In [106]:
# type conversion
boolean_array = np.array([
    [True, False],
    [True, False],
], dtype = np.bool_)
boolean_array.astype(np.int32)

array([[1, 0],
       [1, 0]], dtype=int32)

In [107]:
# type coercion
np.array(["hello",32, 54.21, False]) #it converts all the values to string without telling us

array(['hello', '32', '54.21', 'False'], dtype='<U32')

In [109]:
# type coercion hierarchy

# Adding a float to an array of integers will change all integers into float
np.array([0,43, 23]).dtype

dtype('int64')

# **Shapeshifting**

**array attribute:**


*  shape

**Array methods:**


1.   .flatten()
2.   .reshape()





Finding an array's shape

In [33]:
array = np.random.random((3,5))
print(array)

[[0.47036927 0.60128968 0.89897859 0.12916119 0.24877391]
 [0.51369194 0.66051157 0.29339138 0.96488421 0.25721784]
 [0.58011529 0.36522448 0.82956864 0.73454906 0.8616696 ]]


In [34]:
array.shape

(3, 5)

Falttening an array

In [35]:
array = np.zeros((5,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
array.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Reshaping an array

In [37]:
array.reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **Arithmetic with NumPy Arrays**

**Basic operations:** Create two NumPy arrays with random numbers of the same shape, and then perform element-wise addition, subtraction, multiplication, and division on them.

In [84]:
# create two arrays with random numbers
arr1 = np.random.randint(1, 11, size=(3,3))
arr2 = np.random.randint(1, 11, size=(3,3))

# perform element-wise arithmetic operations
addition = arr1 + arr2
substraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2 

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", substraction)
print("Element-wise multiplication:\n", multiplication)
print("Element-wise division:\n", division)

Array 1:
 [[6 5 1]
 [9 6 6]
 [8 5 7]]
Array 2:
 [[ 8 10  6]
 [ 2  1  3]
 [ 6  3  1]]
Element-wise addition:
 [[14 15  7]
 [11  7  9]
 [14  8  8]]
Element-wise subtraction:
 [[-2 -5 -5]
 [ 7  5  3]
 [ 2  2  6]]
Element-wise multiplication:
 [[48 50  6]
 [18  6 18]
 [48 15  7]]
Element-wise division:
 [[0.75       0.5        0.16666667]
 [4.5        6.         2.        ]
 [1.33333333 1.66666667 7.        ]]


**Practice task 1** 

Create a NumPy array of numbers from 1 to 10, and then reshape it into a 2D array with 5 rows and 2 columns. Perform the following operations on the array:

*   Compute the transpose of the array
*   Compute the dot product of the array with its transpose
*   Compute the element-wise exponential of the array

In [87]:
arr = np.arange(1, 11).reshape(5, 2)

arr_T = arr.T
arr_dot = np.dot (arr , arr_T)
arr_exp = np.exp(arr)

print("Original array:\n", arr)
print("Transpose:\n", arr_T)
print("Dot product with transpose:\n", arr_dot)
print("Element-wise exponential:\n", arr_exp)

Original array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transpose:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
Dot product with transpose:
 [[  5  11  17  23  29]
 [ 11  25  39  53  67]
 [ 17  39  61  83 105]
 [ 23  53  83 113 143]
 [ 29  67 105 143 181]]
Element-wise exponential:
 [[2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04]]


**Practice Task 2:**

1. Create two 1D arrays of length 5, a and b, with random integer values between 0 and 9 (inclusive). Multiply a by b element-wise using the * operator, and store the result in a new array called c bold text.

2. Create a 2D array arr of shape (3, 4) with random integer values between 0 and 9 (inclusive). Subtract the mean of each row of arr from the respective row of arr using the np.mean() and - operators, and store the result in a new array called modified_arr.

3. Create two 2D arrays, arr1 and arr2, both of shape (3, 3), with random integer values between 0 and 9 (inclusive). Compute the element-wise product of arr1 and arr2 using the * operator, and store the result in a new array called product. Divide each element of product by the sum of its row using the np.sum() and / operators, and store the result in a new array called normalized_product.

4. Create a 2D array arr of shape (5, 5) with random integer values between 0 and 9 (inclusive). Multiply the first row of arr by the last row of arr element-wise using the * operator, and store the result in a new array called result.

5. Create a 3D array arr of shape (2, 3, 4) with random integer values between 0 and 9 (inclusive). Compute the mean of each 2D slice along the third dimension of arr using the np.mean() function, and store the result in a new 2D array called mean_arr.

In [67]:
a = np.random.randint(0,10 , size=5)
b = np.random.randint(0,10 , size=5)
c= a*b
print(c)


[20  0 48 56 28]


In [80]:
array_2D = np.random.randint(0,10,size= (3,4))
mean_rows = np.mean(array_2D, axis=1, keepdims=True)
modified_arr = array_2D - mean_rows
print(modified_arr)

[[-2.75  1.25  2.25 -0.75]
 [-0.25  1.75 -3.25  1.75]
 [-1.25  2.75 -2.25  0.75]]


In [79]:
arr1 = np.random.randint(1,10, size= (3,3))
arr2 = np.random.randint(1,10, size= (3,3))
product = arr1 * arr2
print(f"The product of the arrays: \n {product}")
normalized_product = product / (np.sum(product,axis=1, keepdims=True))
print(f"\nThe normalized product of the arrays: \n {normalized_product}")


The product of the arrays: 
 [[ 4 63  3]
 [14 14 18]
 [ 8  5 30]]

The normalized product of the arrays: 
 [[0.05714286 0.9        0.04285714]
 [0.30434783 0.30434783 0.39130435]
 [0.18604651 0.11627907 0.69767442]]


In [78]:
arr_2D = np.random.randint(0,10, size = (5, 5))
result = arr_2D[0] * arr_2D[-1]
print(result)

[ 1  6 24 40  0]


In [81]:
arr_3D = np.random.randint(0,10, size = (2,3,4))
mean_arr = np.mean(arr_3D, axis = 2)
print(mean_arr)

[[5.5  4.75 5.5 ]
 [3.25 2.25 4.25]]


**Practice task 3:**

*  Create two 2D arrays, arr1 of shape (4, 3) and
arr2 of shape (3, 2), with random integer values between 0 and 9 (inclusive). Compute the dot product of arr1 and arr2 using the np.dot() function, and store the result in a new array called dot_product.

*  Subtract the mean of each column of dot_product from the respective column of dot_product using the np.mean() and - operators, and store the result in a new array called modified_dot_product.

*  Create a new array result with shape (2, 2) by selecting the top-left and bottom-right elements of modified_dot_product. Print all arrays.

In [59]:
import numpy as np

# create arr1 and arr2
arr1 = np.random.randint(0, 10, size=(4, 3))
arr2 = np.random.randint(0, 10, size=(3, 2))

# compute the dot product of arr1 and arr2
dot_product = np.dot(arr1, arr2)

# subtract the mean of each column of the dot product from the respective column of the dot product
mean_cols = np.mean(dot_product, axis=0)
modified_dot_product = dot_product - mean_cols

# create a new array result with shape (2, 2) by selecting the top-left and bottom-right elements of the modified dot product
result = np.array([[modified_dot_product[0, 0], modified_dot_product[0, -1]],
                   [modified_dot_product[-1, 0], modified_dot_product[-1, -1]]])

# print the arrays
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("dot_product:\n", dot_product)
print("modified_dot_product:\n", modified_dot_product)
print("result:\n", result)

arr1:
 [[0 2 4]
 [5 6 6]
 [9 3 8]
 [8 2 1]]
arr2:
 [[2 6]
 [9 4]
 [8 7]]
dot_product:
 [[ 50  36]
 [112  96]
 [109 122]
 [ 42  63]]
modified_dot_product:
 [[-28.25 -43.25]
 [ 33.75  16.75]
 [ 30.75  42.75]
 [-36.25 -16.25]]
result:
 [[-28.25 -43.25]
 [-36.25 -16.25]]


# **Basic Indexing and Slicing in numpy**

**Indexing:** Selecting a specific element from an array

In [88]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])  # Output: 3

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1, 2])  # Output: 6

3
6


**Slicing:** Extracting a subset of an array

In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # extracting the elements from 2nd to 4th position

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[:2, 1:])  # extracting the first 2 rows and second and 3rd column of these rows

[2 3 4]
[[2 3]
 [5 6]]


**Boolean indexing:** Selecting elements based on a condition

In [90]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])  # Output: [4, 5]

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[arr2 > 5])  # Output: [6, 7, 8, 9]

[4 5]
[6 7 8 9]


**Practice task:**



1.   Create a NumPy array of shape (5, 5) with random integers between 1 and 10.
2.   Print the element at position (3, 4) of the array.
3.   Slice the array to extract the first row and the first two columns.
4.   Slice the array to extract the elements in the second and third rows and the last two columns.
5.   Create a boolean mask to select all elements in the array that are greater than or equal to 5.
6.   Use the boolean mask to select all elements in the array that are greater than or equal to 5.
7.   Use the boolean mask to replace all elements in the array that are greater than or equal to 5 with -1.
8.   Print the final array to verify that the elements selected in step 7 have been replaced with -1.



In [98]:
# Create a NumPy array of shape (5, 5) with random integers between 1 and 10
arr = np.random.randint(1, 11, size=(5, 5))
print("Original array:\n", arr)

# Print the element at position (3, 4) of the array
print("\nElement at position (3, 4):", arr[3, 4])

# Slice the array to extract the first row and the first two columns
slice1 = arr[0, :2]
print("\nFirst row and first two columns:\n", slice1)

# Slice the array to extract the elements in the second and third rows and the last two columns
slice2 = arr[1:3, -2:]
print("\nElements in the second and third rows and last two columns:\n", slice2)

# Create a boolean mask to select all elements in the array that are greater than or equal to 5
mask = arr >= 5
print("\nBoolean mask:\n", mask)

# Use the boolean mask to select all elements in the array that are greater than or equal to 5
greater_than_5 = arr[mask]
print("\nElements greater than or equal to 5:\n", greater_than_5)

# Use the boolean mask to replace all elements in the array that are greater than or equal to 5 with -1
arr[mask] = -1

# Print the final array to verify that the elements selected in step 7 have been replaced with -1
print("\nFinal array:\n", arr)

Original array:
 [[10  2  3  3  5]
 [ 9  8  9  4  1]
 [ 8  2  8  2  7]
 [ 6  1  4 10  4]
 [ 3  1  1  5  5]]

Element at position (3, 4): 4

First row and first two columns:
 [10  2]

Elements in the second and third rows and last two columns:
 [[4 1]
 [2 7]]

Boolean mask:
 [[ True False False False  True]
 [ True  True  True False False]
 [ True False  True False  True]
 [ True False False  True False]
 [False False False  True  True]]

Elements greater than or equal to 5:
 [10  5  9  8  9  8  8  7  6 10  5  5]

Final array:
 [[-1  2  3  3 -1]
 [-1 -1 -1  4  1]
 [-1  2 -1  2 -1]
 [-1  1  4 -1  4]
 [ 3  1  1 -1 -1]]


# **Mathematical and Statistical Methods:**

In [99]:
# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Compute the sum of all elements in the array
print("Sum:", np.sum(arr))

# Compute the mean of all elements in the array
print("Mean:", np.mean(arr))

# Compute the standard deviation of all elements in the array
print("Standard deviation:", np.std(arr))

# Compute the minimum value of all elements in the array
print("Minimum:", np.min(arr))

# Compute the maximum value of all elements in the array
print("Maximum:", np.max(arr))

# Compute the index of the minimum value in the array
print("Index of minimum:", np.argmin(arr))

# Compute the index of the maximum value in the array
print("Index of maximum:", np.argmax(arr))

# Compute the median value of all elements in the array
print("Median:", np.median(arr))

# Compute the 25th and 75th percentiles of all elements in the array
print("25th percentile:", np.percentile(arr, 25))
print("75th percentile:", np.percentile(arr, 75))

# Compute a histogram of the values in the array using 3 bins
hist, bins = np.histogram(arr, bins=3)
print("Histogram:", hist)
print("Bins:", bins)

Sum: 45
Mean: 5.0
Standard deviation: 2.581988897471611
Minimum: 1
Maximum: 9
Index of minimum: 0
Index of maximum: 8
Median: 5.0
25th percentile: 3.0
75th percentile: 7.0
Histogram: [3 3 3]
Bins: [1.         3.66666667 6.33333333 9.        ]
