<a href="https://colab.research.google.com/github/ayesha-119/Deep-Learning-BWF/blob/master/Task_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🔴 Task 31**

**Topics: Applying One-Hot Encoding and Word Embeddings**


Resource: https://drive.google.com/file/d/1i9dPxM_1M4HYN5bYxFcuklC1vM0GrOCq/view?usp=share_link

Steps to follow:

Convert the text to Lower Case

Word Tokenize

Get its integer value i.e the position by using LabelEncoder()

Get one hot encoding of the word by referring to the label encoded values by using to_categorical()

In [3]:
from keras.preprocessing.text import Tokenizer

text_list  = ['the cat sat on the mat','The dog ate my chocolate']
tokenizer = Tokenizer(num_words= 1000)
# builds word index
tokenizer.fit_on_texts(text_list)

# turns text into list of integer indices
tokenizer.texts_to_sequences(text_list)

one_hot_vectors = tokenizer.texts_to_matrix(text_list,mode = 'binary')
print(one_hot_vectors)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


**Train our own word embedding on data for our problem**

In [4]:
from numpy import array
docs = ['Well done!',
'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
'Weak','Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [5]:
# integer encode the documents
from keras.preprocessing.text import one_hot
# keras.preprocessing.text.one_hot(text, n, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ')
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[14, 6], [21, 7], [24, 24], [18, 7], [13], [14], [40, 24], [23, 21], [40, 7], [36, 22, 6, 22]]


In [7]:
# padding sequence
from keras.utils import pad_sequences
# keras.preprocessing.sequence.pad_sequences(sequences, maxlen=None, dtype='int32', padding='pre', truncating='pre', value=0.0)
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[14  6  0  0]
 [21  7  0  0]
 [24 24  0  0]
 [18  7  0  0]
 [13  0  0  0]
 [14  0  0  0]
 [40 24  0  0]
 [23 21  0  0]
 [40  7  0  0]
 [36 22  6 22]]


In [8]:
# Defining Embedding layer in keras
from keras.models import Sequential
from keras.layers import Embedding, Flatten,Dense

model = Sequential()
model.add(Embedding(vocab_size, 8, input_length = max_length))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)