<a href="https://colab.research.google.com/github/ayesha-119/Deep-Learning-BWF/blob/master/Task_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🔴 Task 12**

**Topics: Broadcasting in Numpy Array**

Resource: https://drive.google.com/file/d/1ILp88f3u_KgJ_nlhTSsAVGdmZlICGhhd/view?usp=share_link



Directions: The Broadcasting concepts are available in Numpy Appendix A: Advanced Numpy Section of the resource.

# **Broadcasting is a powerful tool in NumPy that allows for performing element-wise operations on arrays with different shapes, without having to explicitly reshape or pad the arrays.**

**Adding Two Arrays with the Same Shape**

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


**Multiplying Two Arrays with the Same Shape**

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print(c)

[ 4 10 18]


**Adding Two Arrays with Different Sizes**

In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4])

c = a + b
print(c)

[5 6 7]


**Adding Two Arrays with Different Number of Dimensions**

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

c = a[:, np.newaxis] + b.T
print(c)

[[ 5  8]
 [ 7 10]
 [ 9 12]]


**Multiplying Two Arrays with Different Shapes**

In [13]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])

c = a * b
print(c)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Computing Outer Product of Two Arrays**

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.outer(a, b)
print(c)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Adding a Scalar to an Array**

In [15]:
a = np.array([1, 2, 3])

c = a + 5
print(c)

[6 7 8]


**Subtracting a Scalar from an Array**

In [16]:
import numpy as np

a = np.array([1, 2, 3])

c = a - 2
print(c)

[-1  0  1]


**Multiplying a Scalar with an Array**

In [17]:
import numpy as np

a = np.array([1, 2, 3])

c = a * 3
print(c)

[3 6 9]


**Dividing an Array by a Scalar**

In [18]:
import numpy as np

a = np.array([3, 6, 9])

c = a / 3
print(c)

[1. 2. 3.]


**Broadcasting in Higher Dimensions**

In [19]:
import numpy as np

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([1, 2])

c = a + b[:, np.newaxis, np.newaxis]
print(c)


[[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]


**Setting Array Values by Broadcasting**

In [20]:
a = np.zeros((3, 3))
b = np.array([1, 2, 3])

a[:, :] = b[:, np.newaxis]
print(a)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
